---
name: Packer

on:
  push:

jobs:
  validate:
    runs-on: ubuntu-20.04
    name: packer-validate

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # validate templates
      - name: Validate Template
        run: |
          make packer-fmt
          make packer-validate

  build:
    needs: validate
    runs-on: ubuntu-20.04
    name: packer-build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create secrets file
        run: |
          echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .packer.env
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .packer.env
          echo PACKER_LOG=1 >> .packer.env

      # build artifact
      - name: Build Artifact
        run: make packer-build
